### ISSUE TITLE
Fails to build on FreeBSD

### ISSUE THREAD

**Issue by nunotexbsd** [awslabs/aws-checksums#94]
### Describe the bug

Fails to build on FreeBSD/Clang 18.1.6 amd64:

```
FAILED: CMakeFiles/aws-checksums.dir/source/intel/intrin/crc32c_sse42_avx512.c.o
/usr/bin/cc -DAWS_CHECKSUMS_EXPORTS -DAWS_CHECKSUMS_USE_IMPORT_EXPORT -DAWS_COMMON_USE_IMPORT_EXPORT -DHAVE_SYSCONF -DINTEL_NO_ITTNOTIFY_API -Daws_checksums_EXPORTS -I/wrkdirs/usr/ports/devel/aws-checksums/work/aws-checksums-0.1.19/include -isystem /usr/local/include -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing  -DNDEBUG -std=gnu99 -fPIC -Wall -Wstrict-prototypes -Wextra -pedantic -Wno-long-long -fPIC -Wgnu -Wno-gnu-zero-variadic-macro-arguments -fvisibility=hidden   -mavx512f -mvpclmulqdq -mavx512vl -mavx -mavx2 -mpclmul -msse4.2 -MD -MT CMakeFiles/aws-checksums.dir/source/intel/intrin/crc32c_sse42_avx512.c.o -MF CMakeFiles/aws-checksums.dir/source/intel/intrin/crc32c_sse42_avx512.c.o.d -o CMakeFiles/aws-checksums.dir/source/intel/intrin/crc32c_sse42_avx512.c.o -c /wrkdirs/usr/ports/devel/aws-checksums/work/aws-checksums-0.1.19/source/intel/intrin/crc32c_sse42_avx512.c
/wrkdirs/usr/ports/devel/aws-checksums/work/aws-checksums-0.1.19/source/intel/intrin/crc32c_sse42_avx512.c:51:25: error: size of array element of type 'zalign_8' (aka 'const unsigned long') (8 bytes) isn't a multiple of its alignment (64 bytes)
   51 |     static zalign_8 k1k2[8] = {
      |                         ^
/wrkdirs/usr/ports/devel/aws-checksums/work/aws-checksums-0.1.19/source/intel/intrin/crc32c_sse42_avx512.c:53:25: error: size of array element of type 'zalign_8' (aka 'const unsigned long') (8 bytes) isn't a multiple of its alignment (64 bytes)
   53 |     static zalign_8 k3k4[8] = {
      |                         ^
/wrkdirs/usr/ports/devel/aws-checksums/work/aws-checksums-0.1.19/source/intel/intrin/crc32c_sse42_avx512.c:55:26: error: size of array element of type 'zalign_8' (aka 'const unsigned long') (8 bytes) isn't a multiple of its alignment (64 bytes)
   55 |     static zalign_8 k9k10[8] = {
      |                          ^
/wrkdirs/usr/ports/devel/aws-checksums/work/aws-checksums-0.1.19/source/intel/intrin/crc32c_sse42_avx512.c:57:25: error: size of array element of type 'zalign_8' (aka 'const unsigned long') (8 bytes) isn't a multiple of its alignment (64 bytes)
   57 |     static zalign_8 k1k4[8] = {
      |                         ^
4 errors generated.
```
Full log: 
[aws-checksums-0.1.19,1.log](https://github.com/user-attachments/files/16907034/aws-checksums-0.1.19.1.log)

Thanks

### Expected Behavior

Build OK

### Current Behavior

Fails to Build

### Reproduction Steps

cd devel/aws-checksums && make (ports framework)

### aws-checksums version used

0.1.19

### Compiler and version used

Clang 18.1.6

### Operating System and version

FreeBSD 15 amd64

**Comment by DmitriyMusatkin** [comment]
Sorry about that, Im working on the fix. Will add freebsd ci to this repo as well.

**Comment by DmitriyMusatkin** [comment]
fixed in https://github.com/awslabs/aws-checksums/pull/96
